import type { Metadata } from "next";
import "./globals.css";
import GlobalProvider from "@/providers/GlobalProvider";
import NextTopLoader from "nextjs-toploader"
import { Toaster } from "react-hot-toast";
import { Poppins } from 'next/font/google';




 
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "MachMakers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} antialiased`}
        >
          <NextTopLoader
          //color="#2299DD"
          color="#EC4899"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          //shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          shadow="0 0 10px #EC4899,0 0 5px #EC4899"
        />
        {children}
         <Toaster  position="top-center"/>
        </body>
      </html>
    </GlobalProvider>
  );
}
